SELECT * FROM dbo.TBCIDADE
SELECT NOME_CIDADE FROM DBO.TBCIDADE
SELECT * FROM DBO.TBCIDADE WHERE ID_CIDADE>5
SELECT * FROM DBO.TBCIDADE WHERE NOME_CIDADE= 'SOROCABA'
SELECT * FROM DBO.TBCIDADE WHERE NOME_CIDADE LIKE '%A'
SELECT * FROM DBO.TBCIDADE WHERE NOME_CIDADE LIKE 'A%'
SELECT * FROM DBO.TBCIDADE WHERE NOME_CIDADE LIKE '%A%'
INSERT INTO DBO.TBCIDADE VALUES ('SANTOS', 'SP')
UPDATE DBO.TBCIDADE SET NOME_CIDADE='RIO BRANCO', UF_CIDADE='AC' WHERE ID_CIDADE=10
DELETE FROM DBO.TBCIDADE WHERE ID_CIDADE=10